spring.application.name=demo
# for https
server.forward-headers-strategy=framework 

spring.datasource.url=jdbc:mysql://localhost:3306/humagraph_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=15062006
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=NzI4OWQxN2E4NzY1NlA1Y2JmODUyOTQxZmI5NTK2YmE0NTQxNmUyMzEyMzQ1Njc4OTA7
jwt.expiration=86400000
